import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "GeoQuery AI",
  description: "Conversational Spatial SQL Engine via MCP Server",
};

// Typed as { children: React.ReactNode } rather than the newer LayoutProps<>
// helper — that helper is only generated by `next dev`/`build`/`typegen`,
// which would make `npm run typecheck` fail on a clean checkout that hasn't
// run either yet. This form has no such bootstrapping requirement.
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
